server:
    port: 8080

spring:
    datasource:
        url: jdbc:postgres://postgres1:A57LGpxZCIO59qJKSIKfIteZB1B5xcfx@dpg-cperjglds78s73flp9i0-a/fatecjava
        driver-class-name: org.postgresql.Driver
        initialize: true

    jpa: 
        hibernate:
            ddl-auto: create-drop
            generate-ddl: true

    sql:
        init:
            schema-locations: classpath:/schema-postgresql.sql
            mode: always
            platform: postgres
